apiVersion: v1
entries:
  catalog:
  - created: 2018-05-23T11:16:48.380038+02:00
    description: service-catalog API server and controller-manager helm chart
    digest: 3bf05bebb4f2d124361e6edfc0b8bcbc8423fc5350dc5527b501fda57b927181
    name: catalog
    urls:
    - https://raw.githubusercontent.com/niklaushirt/servicebroker/master/charts/repo/stable/catalog-0.0.1.tgz
    version: 0.0.1
  ups-broker:
  - created: 2018-05-23T11:16:48.380419+02:00
    description: User-provided service-broker deployment Helm chart.
    digest: 2b62e5368faeace38d6ec0ba2f5bdd83cfd6be38729f441cdaad9cfb957edc3d
    name: ups-broker
    urls:
    - https://raw.githubusercontent.com/niklaushirt/servicebroker/master/charts/repo/stable/ups-broker-0.1.19.tgz
    version: 0.1.19
generated: 2018-05-23T11:16:48.378851+02:00
